### ISSUE TITLE
Final Screen Bug

### ISSUE THREAD

**Issue by shananas** [thundrio-kh/kh2-cutscene-remover#4]
When killing final xemnas and the last cutscenes are skipped the final screen doesnt load it stays white and all the text it at the top right. Also no input works neither save or return to title screen.
https://www.twitch.tv/videos/968573708

**Comment by shananas** [comment]
In my recent runs with the updated cutscene skipper the game now crashes once beating Final Xemnas consistently.
https://www.twitch.tv/videos/980489278
This has a few times checking and the end of the video I turned off the dusk model I was using in case that was the issue.
The dusk model doesnt crash on its own.

**Comment by snelson3** [comment]
Fixed
